spring:
  application:
    name: ghn-service
  config:
    import: "optional:configserver:http://localhost:1000"
security:
  allowedOrigins:

---
spring:
  config:
    activate:
      on-profile:
      - localhost
    import: "optional:configserver:http://192.168.1.10:1000"

---
spring:
  config:
    activate:
      on-profile:
      - development
    import: "optional:configserver:http://192.168.1.9:1000"

---
spring:
  config:
    activate:
      on-profile:
      - production
    import: "optional:configserver:http://192.168.1.9:1000"